version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: commerce_postgres
    environment:
      POSTGRES_USER: commerce
      POSTGRES_PASSWORD: commerce123
      POSTGRES_DB: commerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - commerce_network

  redis:
    image: redis:7-alpine
    container_name: commerce_redis
    ports:
      - "6379:6379"
    networks:
      - commerce_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: commerce_app
    environment:
      DATABASE_URL: postgresql://commerce:commerce123@postgres:5432/commerce
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - commerce_network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:

networks:
  commerce_network:
    driver: bridge